name: Auto Build Lanmitm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Lanmitm source
        run: |
          git clone https://github.com/dalufine/Lanmitm.git
          cd Lanmitm
          ls -al

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK
        working-directory: Lanmitm
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Lanmitm-debug-apk
          path: Lanmitm/app/build/outputs/apk/debug/*.apk
